<a href="https://colab.research.google.com/github/kn-neelalohitha/Learning-Numpy/blob/master/Introduction_to_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Numpy

## A Python List is more than just List

In [0]:
L = list(range(10)) # Create a list L [0, 10)
L # Display L in jupyter shell's o/p

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
type(L[0])

int

In [0]:
# Create list of strings

L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [0]:
# type(L2) == type(L1)

True

In [0]:
type(L2[0])

str

In [0]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [0]:
''' 
This is the equivalent code for the code in above cell
L4 = []
for item in L3 :
  L4.append(type(item))
 
L4
''' 

' \nL4 = []\nfor item in L3 :\n  L4.append(type(item))\n \nL4\n'

## Fixed -Type Arrays in Python

In [0]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Some Errors to follow**

In [0]:
import array
L = list(range(10))
A = array.array('a', L)
A

ValueError: ignored

In [0]:
import array
L = list(range(10))
A = array.array(L)
A

TypeError: ignored

In [0]:
import array
L = list(range(10))
L.append('cat')
A = array.array('f', L)
A

TypeError: ignored

In [0]:
import array
L = list(range(10))
L.append(1.0)
A = array.array('f', L)
A

array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 1.0])

array --> efficient storage of data <br>
Numpy --> efficient operations on that data

In [0]:
import numpy as np # numpy --> package, np --> alias 

In [0]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [0]:
# upcast

np.array([3.14, 2, 4, 5])

array([3.14, 2.  , 4.  , 5.  ])

In [0]:
# Explicitly set the data type
# np.array(<[list]>, dtype = <'data-type'>)

np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [0]:
# Nested list result in multi-dimensional array

np.array([range(i, i + 3) for i in [2, 4, 6]])
# [list(range(i, i + 3)) for i in [2, 4, 6]] --> creates [[2, 3, 4], [4, 5, 6], [6, 7, 8]]

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The inner lists are treated as rows of the resulting two-dimensional array.

In [0]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Creating Arrays from Scratch

In [0]:
# Create a length- 10 integer array filled with zeros
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
#Create a length 10 integer array filled with zeros without using numpy
shape = 10
L=[]
for i in range(shape):
  L.append(0)
L

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [0]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3, 5), dtype = float)
# np.ones((row, column), dtype = data-type), here row = 3, column = 5, data-type = float
# !

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
# Create a 3x5 floating-point array filled with 1s without numpy
row = 3 # num of rows
col = 5 # num 0f columns
shape = (row, col) # shape of array
L = [] # empty list
for i in range(shape[1]):
  L.append(1.)
M = [L for i in range(shape[0])]
M

[[1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0],
 [1.0, 1.0, 1.0, 1.0, 1.0]]

In [0]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [40]:
# Create a 3x5 floating-point array filled with 3.14 without numpy
row = 3 # num of rows
col = 5 # num 0f columns
shape = (row, col) # shape of array
# L = [3.14 for i in range(shape[1])]
# M = [L for i in range(shape[0])]

M = [ [3.14 for i in range(shape[1])] for i in range(shape[0])] # required array

M

[[3.14, 3.14, 3.14, 3.14, 3.14],
 [3.14, 3.14, 3.14, 3.14, 3.14],
 [3.14, 3.14, 3.14, 3.14, 3.14]]

In [0]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
# without numpy 
[i for i in range(0, 20, 2)] # creates a list (like array but datatype is list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [0]:
# without numpy
L = []
for i in range(20):
  if (i % 2 == 0):
    L.append(i)

array.array('i',L)


array('i', [0, 2, 4, 6, 8, 10, 12, 14, 16, 18])

In [0]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:
L =[]
start = 0 # lower limit
stop = 1 # upper limit
num = 5 # Number of values
L.append(start)
for i in range(num):
  if(i < num - 1):
    L.append(L[i] + ((start + stop) / (num - 1)))

[float (i) for i in L] # [0.0, 0.25, 0.5, 0.75, 1.0]
#L Ouputs [0, 0.25, 0.5, 0.75, 1.0]
  

[0.0, 0.25, 0.5, 0.75, 1.0]

In [0]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
x = np.random.random((3, 3))
x

In [55]:
x

array([[0.02872448, 0.36353987, 0.16837805],
       [0.02787002, 0.35735815, 0.90433813],
       [0.51294521, 0.73151424, 0.14410961]])

In [59]:
# Create a 3x3 array of normally distributed values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.88475402, -0.49645623, -0.77780302],
       [ 0.07469901, -1.66276493, -1.64018542],
       [ 1.34064971,  1.34720788,  0.11201883]])

In [0]:
random.normalvariate??

In [93]:
# 
# Create a 3x3 array of normally distributed values
# with mean 0 and standard deviation 1 without numpy
import random
row = 3
col = 3
shape = (row, col)
L= [[random.normalvariate(0, 1) for i in range(shape[1])] for i in range(shape[0])] # random.normalvariate(mu, sigma) for normal ditribution
print(L)
np.array(L)


[[-0.6789239650916014, 0.018014579957804006, -1.520600832483786], [-0.09436214004922257, -0.30572808902481013, 0.4974079362252265], [-0.22361159229293603, -1.1837136989520574, -0.09296413825623363]]


array([[-0.67892397,  0.01801458, -1.52060083],
       [-0.09436214, -0.30572809,  0.49740794],
       [-0.22361159, -1.1837137 , -0.09296414]])

In [79]:
# Create a 3x3 array of random integers in the interval [0,10)
np.random.randint(0,10,(3, 3))

array([[5, 7, 8],
       [7, 9, 5],
       [7, 7, 7]])

In [89]:
# Create a 3x3 array of random integers in the interval [0,10) without numpy
import random
row = 3
col = 3
shape = (row, col)
L= [[random.randint(0, 10) for i in range(shape[1])] for i in range(shape[0])]
print(L)
np.array(L)

[[7, 3, 7], [5, 2, 2], [9, 7, 1]]


array([[7, 3, 7],
       [5, 2, 2],
       [9, 7, 1]])

In [95]:
# Create a 3x3 identity matrix
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
# Create a 3x3 identity matrix without numpy
def shift (L, k):
  return L[-k : ] + L[ : -k]

dim = 3 # dimension of identity matrix 
L = [0. for i in range(dim)]
L[0] = 1.

M = [shift(L, i)for i in range(dim)]
print(M)
np.array(M)
# np.eye(3)


[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])