<a href="https://colab.research.google.com/github/kn-neelalohitha/Learning-Numpy/blob/master/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# The Basics of Numpy Arrays
* **Attributes** of array
 - size, shape, dimension
* **Indexing** of Array
 - Getting and setting individual array elements 
* **Slicing** of Array
  - Getting and setting of smaller subarrays from larger arrays
* **Reshaping** of Array
 - Changing the shape of array
* **Joining** and **splitting** of Arrays
  - Combining multiple arrays into one and splitting one array into many
  

## Numpy array attributes

In [0]:
import numpy as np
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size = 6) # One-dimensional array 
x2 = np.random.randint(10, size = (3, 4)) # Two-dimensional array 
x3 = np.random.randint(10, size = (3, 4, 5)) # Three-dimensional array


Some important numpy attributes : # of dimension, shape, size

In [2]:
print("x3 ndim: ",x3.ndim)
print("x3 shape: ", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60


In [3]:
print("dtype: ", x3.dtype)

dtype:  int64


In [4]:
print("itemsize: ", x3.itemsize, "bytes")
print("nbytes: ", x3.nbytes, "bytes")

itemsize:  8 bytes
nbytes:  480 bytes


## Array Indexing: Accessing Single Elements 

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0] # first element of the array

5

In [7]:
x1[4] # 5th element of the array 

7

Last element can be accssed using -ve indexing

In [8]:
x1[-1] # Last element

9

In [9]:
x1[-2] # 2nd from last

7

In [10]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

To access items in a multidimensional array we use *comma-separated* **tuple** *of indices* 


The left indices specifies the position of row(array), the right indices specifies the column (the position of element inside the array(row) pointed to by left indices)

In [11]:
# Access first element of x2
x2[0, 0]

3

In [12]:
x2[2, 0] # 1st element of 3rd(index = 2) row 

1

In [13]:
x2[2, -1]

7

We can modify the value of the array using this index notation 

In [14]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [0]:
x2[0, 0] = 12

In [16]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

Numpy array has a fixed data type. If a floating point value is inserted to an integer array it will be truncated

In [17]:
x1[0] = 3.14
x1

array([3, 0, 3, 3, 7, 9])

   ## Array Slicing: Accessing subarray

x[start:stop:step]

**One-Dimensional subarray**

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# first 5 elements
x[: 5]

array([0, 1, 2, 3, 4])

In [20]:
x[ 5:] # elements starting from index 5

array([5, 6, 7, 8, 9])

In [21]:
x[4 : 7] # elements starting from index 4 till 7(excluding 7)

array([4, 5, 6])

In [22]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [23]:
x[1::2]

array([1, 3, 5, 7, 9])

In [24]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
x[5::-2]

array([5, 3, 1])

**Multidimensional Array**

In [26]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [27]:
x2[:2, :3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [28]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [29]:
x2


array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [30]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

**Accessing array rows and column**

In [31]:
print(x2[:, 0])

[12  7  1]


In [32]:
print(x2[0, :])

[12  5  2  4]


In [33]:
print(x2[0])

[12  5  2  4]


**Subarrays as _no-copy_ views**

In [34]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
x2_sub = x2[:2, :2] # first 2 rows and first 2 colums
print(x2_sub)

[[12  5]
 [ 7  6]]


In [36]:
x2_sub[0, 0] = 99 # Modify 1st element of 1st array
print(x2_sub)

[[99  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [38]:
np.random.seed(0)
xA = np.random.randint(10, size=(3,4))
xA

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [39]:
xA_sub = xA[ ::, 1:]
print(xA_sub)

[[0 3 3]
 [9 3 5]
 [4 7 6]]


In [40]:
xA_sub[1,2] = 1
print(xA_sub)

[[0 3 3]
 [9 3 1]
 [4 7 6]]


In [41]:
print(xA)

[[5 0 3 3]
 [7 9 3 1]
 [2 4 7 6]]


In [42]:
# Change the values in sub-array the same is reflected in original array
xA_sub[2,2] = 5 
xA_sub[0,2] =9
print(xA)

[[5 0 3 9]
 [7 9 3 1]
 [2 4 7 5]]


In [43]:
print(xA_sub)

[[0 3 9]
 [9 3 1]
 [4 7 5]]


In [44]:
# change the value (common to subarray) in original array
xA[0, 2] = 6 
print(xA)

[[5 0 6 9]
 [7 9 3 1]
 [2 4 7 5]]


In [45]:
print(xA_sub) # the change in main array is reflected in subarray

[[0 6 9]
 [9 3 1]
 [4 7 5]]


**Creating copies of arrays**
This is done using `copy()` method

In [46]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [47]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [48]:
print(x2) # No change in x2

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping Arrays

This is usually done using `reshape` method.

In [49]:
x = np.arange(1,10).reshape((3, 3)) # np.arange o/ps 1D -array([1, 2, 3, ..., 9]) with 9 elements in range [1, 10). o/ps 3x3 array when 
                                # reshape() method is used for changing shape
print(x) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Another usecase of reshaping is converting 1D vector into 2D column or row vector. This can be achieved using `reshape` method or `newaxis` keyword in slice operator

In [50]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [51]:
# Converts x into 2D row-vector using reshape()
x.reshape((1, 3))

array([[1, 2, 3]])

In [52]:
# Converts x into 2D row-vector using mewaxis keyword
x[np.newaxis, :]

array([[1, 2, 3]])

In [53]:
# Converts x into 2D col-vector using reshape()
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [54]:
# Converts x into 2D col-vector using newaxis keyword
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

Whenever possible reshape uses _no-copy_ view of the initial array

In [55]:
x

array([1, 2, 3])

In [0]:
x_copy = x.reshape((3,1))

In [0]:
x_copy[1, 0] = 8

In [58]:
x_copy

array([[1],
       [8],
       [3]])

In [59]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [60]:
x_copy_na = x[:, np.newaxis] # na -> newaxis created using newaxis keyword
print(x_copy_na)


[[1]
 [2]
 [3]]


In [0]:
x_copy_na[2,0] = 65

In [62]:
x

array([ 1,  2, 65])

In [63]:
x_copy

array([[1],
       [8],
       [3]])

Though `x_copy` and `x_copy_na` are created using different ways(`reshape` and `newaxis`) modifying a value in any one of them is **reflected back** in the other and in the initial array(`x`) from which they are created. 

## Array Concatenation and Splitting

In [0]:
??np.concatenate

In [65]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y]) # o/ps array([1, 2, 3, 3, 2, 1])

array([1, 2, 3, 3, 2, 1])

In [0]:
z = np.array([99, 99, 99])

In [67]:
print(np.concatenate([x,y,z]))

[ 1  2  3  3  2  1 99 99 99]


2D arrays

In [0]:
grid = np.array([[1, 2, 3], 
                [4, 5, 6]])

In [69]:
print(np.concatenate([grid, grid]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [70]:
# concatenate along second axis
np.concatenate([grid,grid], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For arrays of mixed dimensions `hstack` and `vstack` is used

In [71]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                [6, 5, 4]])
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [72]:
np.vstack([grid, x])

array([[9, 8, 7],
       [6, 5, 4],
       [1, 2, 3]])

In [73]:
y = np.array([[99],
    [99]])
np.hstack([ grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [74]:
np.hstack([y, grid])

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

**splitting arrays**

In [75]:
x = [1, 2, 3, 99, 99,3 , 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) # 3 and 5 split indices => x2 starts at x[3], x3 starts at x[5]
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [76]:
grid = np.arange(16).reshape((4,4))
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [78]:
# split grid into 2 subarrays row wise
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [0]:
# split grid into 2 subarrays col-wise
left, right = np.hsplit(grid, [2])

In [80]:
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [81]:
# np.split creates no-copy views
left[0, 1] = 25
print(left)

[[ 0 25]
 [ 4  5]
 [ 8  9]
 [12 13]]


In [82]:
print(grid)

[[ 0 25  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
